name: Publish NuGet packages

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'alpha'
      - 'beta'

jobs:
  get-version:
    name: Get Next Version
    permissions:
      contents: write # semantic-release validates permissions even in dry_run mode, this job only uses read.
    uses: ./.github/workflows/create-release.yml
    with:
      dry_run: true

  build-test:
    name: Build & Test
    needs: get-version
    permissions:
      contents: read
    uses: ./.github/workflows/build-test.yml
    with:
      version: ${{ needs.get-version.outputs.new_release_version }}

  create-release:
    name: Crate Release
    needs: build-test
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: ./.github/workflows/create-release.yml
    with:
      dry_run: false

  publish-nuget:
    name: Publish NuGet
    needs: create-release
    if: needs.create-release.outputs.new_release_published == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

    - name: Download NuGet Packages
      uses: actions/download-artifact@v8
      with:
        name: nuget-packages
        path: nuget-packages

    - name: Display structure of downloaded files
      run: ls -R nuget-packages

    - name: .NET NuGet Push
      env:
        NUGET_API_KEY: ${{ steps.login.outputs.NUGET_API_KEY }}
      run: dotnet nuget push nuget-packages/**/*.nupkg --api-key "$NUGET_API_KEY" --source https://api.nuget.org/v3/index.json
